{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "open-webui.fullname" . }}-secret
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
type: Opaque
stringData:
  WEBUI_SECRET_KEY: {{ .Values.secret.webuiSecretKey | default (randAlphaNum 32) | quote }}
{{- end }}
